#!/usr/bin/env ruby

require_relative("lib/fashion_police")

@fashion_police = FashionPolice.new

everything_hunky_dory = true

ARGV.each do |filename|
  begin
    @fashion_police.investigate(File.read(filename))
  rescue FashionPolice::BadCode
    everything_hunky_dory = false
    puts filename
    puts @fashion_police.errors
  end
end

if everything_hunky_dory
  exit(0)
else
  exit(1)
end

