#!/usr/bin/env ruby

require_relative("lib/fashion_police")

@fashion_police = FashionPolice.new
errors = []

ARGV.each do |filename|
  begin
    @fashion_police.investigate(File.read(filename))
  rescue FashionPolice::BadCode
    errors << filename
    errors << @fashion_police.errors
  end
end

if errors.empty?
  exit(0)
else
  puts "JavaScript style errors!"
  errors.each do |error|
    puts error
  end
  exit(1)
end

